language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
before_install:
  - git submodule update --init --recursive
script: "rake spec"
env:
  - PUPPET_VERSION=2.7.20
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.0
  - PUPPET_VERSION=3.4.3
