language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - ree
before_install:
  - git submodule update --init --recursive
script: "rake spec"
env:
  - PUPPET_VERSION=2.6.12
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.7.9
  - PUPPET_VERSION=3.0.1
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.12
